apiVersion: apps/v1
kind: Deployment
metadata:
  name: b4mad-racing-mosquitto
  annotations:
    original-image-tag.thoth-station.ninja: 2.0.15-openssl
  labels:
    app.kubernetes.io/version: "2.0.15-openssl"
    app: mosquitto
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: docker.io/eclipse-mosquitto@sha256:4ee2d823259ed813fc3761ac63dcf5a940231017bfb6aa4fa74615f63f1a477f
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: mqtt-tls
              containerPort: 8883
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mqtt
          readinessProbe:
            tcpSocket:
              port: mqtt
          resources:
            limits:
              memory: 32Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /mosquitto/config
              name: config
            - mountPath: /mosquitto/password
              name: password
      volumes:
        - configMap:
            defaultMode: 420
            name: mosquitto-config
          name: config
        - secret:
            defaultMode: 420
            secretName: mosquitto
          name: password
      serviceAccount: b4mad-racing-mosquitto
      serviceAccountName: b4mad-racing-mosquitto
