apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mosquitto
spec:
  endpoints:
    - interval: 15s
      port: mosquitto-tcp
      scheme: http
  namespaceSelector:
    matchNames:
      - b4mad-racing
  selector: {}
