kind: Secret
apiVersion: v1
metadata:
    name: grafana-credentials
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:gzGVMmk48zmXdpV3Bpv9nvFFNSU=,iv:xJEiQe4BW6HKwWEGcTIbfzPzcg7nTmxp8Kxirx+lu5w=,tag:gsILj08fcsg4IhY/9Ti4TQ==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:2zWvCXs=,iv:mQCMEAZbtmPOSEc7q93m/6B/UOEWSorF+zclcu2dIXI=,tag:1ZcaGPOtxsWcNjJkuPG0eQ==,type:str]
    #ENC[AES256_GCM,data:JM3p+dHY10lXKph1XwhnaGzY6Xgo7PQiVjRQNjxpA6nQznwpAsXDOxkjevArwSI8hcS6NWNrfiN+tH6TsSSNjkP/Bid7Kg==,iv:02uZfrCE1cq1LmT6CE9gJquuCksOps9wFQjBxUFOW8Y=,tag:C4hkMcjDlDoyrGQYUR5z0g==,type:comment]
    INFLUX_GRAFANA_READER_TOKEN: ENC[AES256_GCM,data:xZmgVB6ROEZSHLCxZszc+MbbJfqBxPjGekyBKlsAzjI13l2fTp9Zdtul+KqGKoLRGwjv5Qp3uDkZ59WDHR74uky6nXCJECo6A2NPHlCIzfjDH97pzVmWzQ==,iv:esO+84dufMLmd5a56u4rGOsUXtcoq2HNKD3jRAsDVTI=,tag:ajo+c96ZOOFv6hSOyiCGhw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-12T15:44:59Z"
    mac: ENC[AES256_GCM,data:ebEcTGK29Ad0G0nJEDWjZ2TpEBZbXKcM94sU9TvMdF9Uuqy5hWk+XhuxdEbyU8hQyBDTdn5XNKmfG3hJwB+jb26zbWO5IZJ98y8sK6+kMr5v/9NINMo9kKGzM6iVJysD48VIHOsDLMUgWVX9YNZjLYKZa9F9T9sKaL6w0VziNvM=,iv:QTf0X2MIdh3G5DtsTU/PuhYGhpuS+hAgR7p+5FLRVHM=,tag:LOr5dc74iZNZQAA4tbLsbw==,type:str]
    pgp:
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYARAArPFbc27LcUeJdSvYg4BjuTyOQODQFf9HwGvSY5rHLWCN
            9xHwlMlT4wSi3uXWvMSH97zq9fei4SgGkgur9Bj0wF2CvZFH2mQcft+uSUoGVrHG
            EUCAXpVPQZT5Bkq4TaGguJad63ljJZSRb3CU13niPlr7wBtkGRjY2yS0jmil/nf2
            D0eiUippz5qBzoUlrK3LQ7yJniQ+xbDVr/1PbaCB2B5l8D1o+6NVZMV2IOrkLg+r
            8MK93F4YCXgvLjxxqsfkHNEWI974tvqLOE5WNMieQWWUgjDpDQMfX/hZ+JZS7mSi
            CmeozIWsgMkWQuR2NhGloVTc6OfJ+WvT/jPQ+qkhAqegmww71XodjoSLinfSkC9H
            v5qh+GyBrGjXZZN72MP3M0ebCVw2Pqq/6hS0FXGkeHPxosDGSHlPcJr+9hrY0Qnr
            iS6pAdaw4Tm54DndCIO9OLtqMxZYEX8ttU3mGdd9NEoENnnBuwU85AaRo+r4QaLs
            N2wLGedmDZa+p6MxObFVq+34RB0f7h3GjCpSX6evqVQVthu8R1iDrQBhUHCPHVZG
            7fy1jH3Tm+8AeZp3e5YBC2zMYDYkmMkYjHGTvZwlW5SVQ4J03aOMzd+QWvWmQwuH
            FzlxHGe1MQXyClBTFmC254+lRS95t5xDrsIgi1bFpCandZQYQFUDkeLLxBoxaKDS
            XgHUe2+5pWvMz3Lt3DalV4fJ50E94krPUUY5Tho6S1WI0K5HADBAzMJErA7zwnZ/
            YrjPihMDyZLN538cr6CJn93FqSYXRbGz84xlaIq4cBEGk9D/PjZaDLc4gnptZ9E=
            =Dugu
            -----END PGP MESSAGE-----
          fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQgAkBGMTyu+ex7BR4uPWSbd8Ssn++tXgcQZmUxqcK8VMq+y
            SW7nHNY/qm/F6aHfPrDsMS2+adEyazMTD85sfgRt1g6jzIvkBsLgNorAHNjITjah
            J79oo8qm81EmqA0R345IptsVSXPpDCTkQeCOGrFFehvcqIk1P/ZabOchEBy5ngSP
            LJCxXRWZ9XQaxuDr5HJGLh+dg3q5BHy65GWHfO1x/f+R607hAoDgU3+fjepwPmn3
            n6/Y0+kEIhHwhNo/YroMxMlEyYNWNL1p3CGlU6IpgC2ojJEAeRWcJk9FmbhwBqm0
            K1He47L0m5+exhc18tt4D7az5BKMRDXLYyW3DqhZ79JeAbuRtS829CZY56dndZpo
            HCKYBe4e8YtqPZ/OBjkUympagRhGhLbgk8kiafh9cbAe9r3KFtqRCM4eNB11z8E1
            UAzzh5/5VD+2MxNi2i3JVPtFMJJ5Cz4VrfqLEx+8bw==
            =rObV
            -----END PGP MESSAGE-----
          fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf5Ab03Dpq0bgKF8/7V694Ebu1pjyg9WukD2gbWmjt8YGk1
            BP+oyES8b7xbahgP9gPhScQHvqWCuYWQVas70lCsSH4kzV3MQbSsGujU76WtUjzY
            CW5wKblX24aqo/8z47ZJtfdkhm5YAXxo/5Engcgn/8yd9ZObyrDeFHnnDwxHfeyQ
            o0Sc5yhRVhtpiqjW3K5Q5vLW/a+K/TECpCQSB65YfaN3Hi+GwB9bxe5qLomacK/f
            afrbmJMwKuyjKxhkSS1y0aCO/b9fkraGWpqAy9TUnsx0vyO6eQxe7/629GefP+ku
            BeGXQSEFYtRImaM6DO5eIgVfkLbwguJeXwRKy6QWn9JeAXsYs7WXrj/uBVshcI8M
            TLrmlixDElaNoF6o7V5tPFVJYmGmKfJspMk+4xtdWWGHkfTKqOG3QaRzjjUozMvd
            HhxSi/X10DY6nuRf7H8KDIwkOaUszHf/F8l5GjfoSQ==
            =6FPY
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
        - created_at: "2022-10-27T12:21:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ/+OftX0hUn1Y1faN7RieqWBDXmst6asiIMUJL8+u742ST6
            2emmvXROzEnVIHM4pR99jzbJ5Op/SaO8UEzGh/fx4dgJnS+2hO4WlrlJ+1oFGD5s
            qZRoy7D8t2Q+QMMrxslakG32dQmckWuq9Mjx9PGDlDeLH7fVr6RUD1vs/tsuBIO9
            BlXfnD8LOtGgIA84mOScgF9V9xx928pMq+nk0LcOb1rfEJ9RZjWMn3R5BlfDvrvs
            ZR93abntyiA8Ye/cS178uwbt9yTm+21ag/30/1kk6DeSkoLivLAjTM5MEcCHvcaZ
            zteGShGLspx0nWNx8LS2FJxWb/5Ii6+lQjX/E7YWGg6v0GNIvNx5TV2V+FLfZ69m
            M3NRmjJapyEZlRtJ1snBPGZpSu0I0wuuaDzB2EAhcm+YHxRgNa1MV2nnZrQl5Una
            XRqiISJTEiW5qK9MG13pzX6zORdUcKQBgcHj1MfGWE4WDdlRgfCrHixsTz7EshGK
            Ih166XjklBNbX+lWAW1sklp4lHByRUintOFz8eZuNHwCad3NTAwx/tSu/KCkgWWP
            /7xGLoUhvNxzPt7BhsijF9gO1pL0brHKqK5i1XlygltPAAQYZzOeqEL5oQQoW2RS
            wmAwLsj2zzTjz1M1TECHVhTHhFVet5ugK/kxK1mBxc0cNpX79ZNLIWJnyBRlv6LS
            XgFEoljpDayw1c19fVEcNBoVtVGeJEiL3TkQ6rvTcPB2jiUbvx3qyILlxrq7MkVz
            /cMnBCPgGAec0aY/UdftdtL/LKCALTtnVwc5UDKVf2mHLqm3nOuEsYuxOrCfuIA=
            =CmXx
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.7.2
