apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#commonLabels:
# FIXME app.kubernetes.io/component: postgresql
resources:
  - route.yaml
  - deployment_config.yaml
  - persistent_volume_claim.yaml
  - service.yaml
  - service_account.yaml
  - service_monitor.yaml
