check:
  - overlays-build
overlays_dir: components
overlays:
  - name: paddock
    build:
      build-stratergy: Containerfile
      dockerfile-path: Containerfile
      registry: quay.io
      registry-org: b4mad
      registry-project: paddock
      registry-secret: b4mad-aicoeci-pusher-pull-secret
    deploy:
      project-org: b4mad
      project-name: racing
      image-name: paddock
      overlay-contextpath: manifests/paddock/overlays/smaug/image_stream_tag.yaml
