check:
  - overlays-build
overlays_dir: components
overlays:
  - name: paddock
    build:
      build-stratergy: Containerfile
      dockerfile-path: paddock/Containerfile
      registry: quay.io
      registry-org: b4mad
      registry-project: paddock
      registry-secret: b4mad-aicoeci-pusher-pull-secret
    deploy:
      project-org: b4mad
      project-name: racing
      image-name: paddock
      overlay-contextpath: manifests/paddock/overlays/smaug/image_stream_tag.yaml
  - name: pitcrew
    build:
      build-stratergy: Source
      base-image: quay.io/thoth-station/s2i-thoth-ubi9-py39:v0.35.1
      registry: quay.io
      registry-org: b4mad
      registry-project: pitcrew
      registry-secret: b4mad-aicoeci-pusher-pull-secret
