check:
  - thoth-build
build:
  build-stratergy: Containerfile
  base-image: quay.io/thoth-station/s2i-thoth-f35-py310@sha256:f2fbf1e0ff31c6f8b1f8ceaccb8b2ada80681d5f9f3f4a157af5dd81ae98b5f5
  dockerfile-path: paddock/Containerfile
  registry: quay.io
  registry-org: b4mad
  registry-project: paddock
  registry-secret: b4mad+aicoeci_pusher
