apiVersion: apps/v1
kind: Deployment
metadata:
  name: b4mad-racing-mosquitto
  annotations:
    original-image-tag.thoth-station.ninja: 2.0.15-openssl
  labels:
    app.kubernetes.io/version: "2.0.15-openssl"
    app: mosquitto
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - env:
            - name: SOLUNAR_WS_LOG_LEVEL
              value: "1"
          name: mosquitto
          image: docker.io/eclipse-mosquitto@sha256:4ee2d823259ed813fc3761ac63dcf5a940231017bfb6aa4fa74615f63f1a477f
          imagePullPolicy: Always
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 8883
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          resources:
            limits:
              memory: 32Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /mosquitto/config
              name: config
      volumes:
        - configMap:
            defaultMode: 420
            name: mosquitto-config
          name: config
      serviceAccount: b4mad-racing-mosquitto
      serviceAccountName: b4mad-racing-mosquitto
