apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  ingress:
    spec:
      # ingressClassName: nginx
      rules:
        - host: pitwall.b4mad.racing
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - pitwall.b4mad.racing
          secretName: core-cert
  client:
    preferIngress: true
  persistentVolumeClaim:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Gi"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: credentials
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  config:
    security:
      allow_embedding: "true"
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "true"
      org_name: Main Org.
      org_role: Viewer
    users:
      allow_sign_up: "true"
    log:
      mode: console
