apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: paddock
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/b4mad/paddock:v0.1.12
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
