apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: paddock
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/b4mad/paddock:v0.1.11
      importPolicy: {}
      referencePolicy:
        type: Local
