apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: pgbouncer
    files:
      - pgbouncer.ini
generators:
  - secret-generator.yaml
