global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

image:
  registry: docker.io
  repository: bitnami/influxdb
  tag: 2.4.0-debian-11-r21
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

architecture: standalone

auth:
  enabled: true
  existingSecret: "influxdb2-auth"
  usePasswordFiles: false
  admin:
    username: admin
    org: b4mad
    bucket: racing
  readUser:
    username: reader
  writeUser:
    username: writer
  createUserToken: false

influxdb:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  resources:
    limits:
      cpu: 8000m
      memory: 16Gi
    requests:
      cpu: 4000m
      memory: 8Gi

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 128Gi
  annotations: {}

serviceAccount:
  enabled: true

metrics:
  # disable as `nable to continue with update: could not get information about the resource: servicemonitors.monitoring.coreos.com "b4mad-racing-influxdb2" is forbidden: User "goern" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "b4mad-racing"`
  enabled: false
  service:
    type: ClusterIP
    port: 9122
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"
      prometheus.io/path: "/metrics"
    externalTrafficPolicy: Cluster

  serviceMonitor:
    enabled: true

backup:
  enabled: true
  directory: "/backups"
  retentionDays: 10
  cronjob:
    schedule: "0 2 * * *"
    historyLimit: 1
    podAnnotations: {}
    securityContext:
      enabled: false
  uploadProviders:
    aws:
      enabled: true
      existingSecret: "influxdb2-backup"
      bucketName: "s3://b4mad-racing-smaug/influxdb"
