apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: telegraf
resources:
  - ../../base
configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf.conf
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
