apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: grafana
generators:
  - secret-generator.yaml
resources:
  - ../../../base/grafana
  - dashboards
  - datasource.yaml
  - route.yaml
