apiVersion: batch/v1
kind: Job
metadata:
  name: rebuild
  namespace: b4mad-racing
spec:
  selector: {}
  template:
    metadata:
      name: rebuild
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: b4mad-racing-pguser-paddock
                  key: uri
          name: rebuild
          envFrom:
            - secretRef:
                name: paddock-settings
          image: paddock:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - python /opt/app-root/src/manage.py maintenance --delete-sessions ; python /opt/app-root/src/manage.py replay --firehose --live --keep-session-id --end 'now()' --start=2023-04-01 --wait=0 --quiet --bucket=fast_laps --measurement=fast_laps --delta=1d ; python /opt/app-root/src/manage.py replay --firehose --live --keep-session-id --end 'now()' --start=-32d --wait=0 --quiet --delta=1h
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Never
