apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
   app.kubernetes.io/component: keycloak
resources:
  - deployment_config.yaml
  - persistent_volume_claim.yaml
  - route.yaml
  - service_account.yaml
  - service_monitor.yaml
  - service.yaml
