apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  baseImage: quay.io/operate-first/grafana:8.4.3
  configMaps:
    - grafana-dashboards
  config:
    security:
      allow_embedding: true
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    users:
      allow_sign_up: true
    log:
      level: warn
      mode: console
    dashboards:
      default_home_dashboard_path: "/etc/grafana-configmaps/grafana-dashboards/landingpage.json"
  dashboardLabelSelector:
    - matchLabels:
        app: grafana
  ingress:
    enabled: false
  dataStorage:
    accessModes:
      - ReadWriteOnce
    size: '1Gi'
    class: ocs-external-storagecluster-ceph-rbd
