apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/influxdb
  - service_monitor.yaml
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - pvc.yaml
  - deployment.yaml
