apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: analyze
  namespace: b4mad-racing
spec:
  schedule: "0 */6 * * *"
  selector: {}
  jobTemplate:
    spec:
      template:
        metadata:
          name: analyze
        spec:
          containers:
            - env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: b4mad-racing-pguser-paddock
                      key: uri
              envFrom:
                - secretRef:
                    name: paddock-settings
              image: paddock:latest
              imagePullPolicy: Always
              name: analyze
              command: ["/bin/sh", "-c"]
              args:
                - python /opt/app-root/src/manage.py analyze --copy-influx
              resources:
                limits:
                  cpu: "2"
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 256Mi
          restartPolicy: Never
