---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/component: telegraf
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app.kubernetes.io/component: telegraf
  template:
    spec:
      containers:
        - env:
            - name: HOSTNAME
              value: telegraf
          image: telegraf:1.22.3
          name: telegraf
          ports:
            - name: metrics
              containerPort: 9090
          volumeMounts:
            - mountPath: /etc/telegraf
              name: config
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
      restartPolicy: Always
      serviceAccount: telegraf
      serviceAccountName: telegraf
      volumes:
        - configMap:
            defaultMode: 420
            name: telegraf-config
          name: config
