apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegraf
spec:
  endpoints:
    - interval: 15s
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - b4mad-racing
  selector:
    matchLabels:
      app.kubernetes.io/component: telegraf
