kind: Job
apiVersion: batch/v1
metadata:
  name: b4mad-racing-influxdb2-backup-manual
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      volumes:
        - name: backup-scripts
          configMap:
            name: b4mad-racing-influxdb2-backup
            defaultMode: 493
        - name: b4mad-racing-influxdb2-backups
          persistentVolumeClaim:
            claimName: b4mad-racing-influxdb2-backups
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: influxdb-backup
          command:
            - /tmp/backup.sh
          env:
            - name: INFLUXDB_ADMIN_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: b4mad-racing-influxdb2
                  key: admin-user-password
            - name: INFLUXDB_ADMIN_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: b4mad-racing-influxdb2
                  key: admin-user-token
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: b4mad-racing-influxdb2-backups
              mountPath: /backups
            - name: backup-scripts
              mountPath: /tmp/backup.sh
              subPath: backup.sh
          terminationMessagePolicy: File
          image: "bitnami/influxdb:2.4.0"
      containers:
        - name: influxdb-backup-dummy-container
          image: "bitnami/influxdb:2.4.0"
          command:
            - /bin/true
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false
