---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitcrew-durandom
  labels:
    pitcrew.b4mad.racing/crewchiefname: durandom
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      pitcrew.b4mad.racing/crewchiefname: durandom
  template:
    metadata:
      labels:
        pitcrew.b4mad.racing/crewchiefname: durandom
    spec:
      containers:
        - env:
            - name: CREWCHIEF_USERNAME
              value: durandom
          image: quay.io/b4mad/pitcrew:main
          name: pitcrew
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pitcrew-durandom
  labels:
    pitcrew.b4mad.racing/crewchiefname: durandom
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
  type: ClusterIP
  selector:
    pitcrew.b4mad.racing/crewchiefname: durandom
