---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitcrew-durandom
  labels:
    app.kubernetes.io/component: pitcrew-durandom
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app.kubernetes.io/component: pitcrew-durandom
  template:
    spec:
      containers:
        - env:
            - name: CREWCHIEF_USERNAME
              value: durandom
          image: quay.io/b4mad/pitcrew:main
          name: pitcrew
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
      restartPolicy: Always
