---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitcrew-goern
  labels:
    pitcrew.b4mad.racing/crewchiefname: goern
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      pitcrew.b4mad.racing/crewchiefname: goern
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        pitcrew.b4mad.racing/crewchiefname: goern
    spec:
      containers:
        - env:
            - name: CREWCHIEF_USERNAME
              value: goern
          image: quay.io/b4mad/pitcrew:latest
          name: pitcrew
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
          ports:
            - name: dash
              containerPort: 8050
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pitcrew-goern
  labels:
    pitcrew.b4mad.racing/crewchiefname: goern
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
  type: ClusterIP
  selector:
    pitcrew.b4mad.racing/crewchiefname: goern
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    pitcrew.b4mad.racing/crewchiefname: goern
  name: pitcrew-goern
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: pitcrew.b4mad.racing
  path: /goern
  tls:
    termination: edge
  to:
    name: pitcrew-goern
