apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: influxdb
resources:
  - service_monitor.yaml
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
